version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  wine:
    docker:
      - image: electronuserland/builder:wine
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn lint
            - run: yarn build
            - run: yarn test
  package-mac:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn package-mac-zip --publish always
  package-linux:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo apt-get install --no-install-recommends -y libopenjp2-tools rpm bsdtar
            - run: yarn install
            - run: yarn package-linux --publish always
  package-windows:
    executor:
      name: wine
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn package-win --publish always

workflows:
  main:
    jobs:
      - build-and-test
      - launch-package:
          type: approval
          requires:
            - build-and-test
          filters:
            branches:
              only: master
      - package-mac:
          requires:
            - launch-package
      - package-linux:
          requires:
            - launch-package
      - package-windows:
          requires:
            - launch-package
